#412 Create django tests to test connection to the Java backend
MetaCell/scidash pull request #147
Opened 2020-01-08 16:38 UTC by zsinnema

# Create django tests to test connection to the Java backend
https://github.com/MetaCell/geppetto-scidash/issues/412

## Changes
feat: added shortcut for python manage command and added variables for easier Makefile maintenance
fix: add missing packages and test coverage packages
fix: add ignore venv to flake8 config file
chore: add run-tests command to Makefile
test: fix tests routines and data
feat: add coverage command to Makefile to show test coverage scidash backend
test: added test to check connection to Virgo server
feat: added run-tests to pre-commit hook
chore: update requirements.txt and pin psycopg2 to 2.7.7
chore: add ignore coverage to .gitignore
test: test if geppetto servlet manager is correctly installed

2020-01-15 17:01 UTC, ddelpiano requested changes

2020-01-15 17:01 UTC, ddelpiano commented on requirements.txt
> -django==1.11.23
@zsinnema I think reverts the upgrade we recently merged in development with the new django version, could you fix this please?
Thx!

2020-01-15 19:33 UTC, zsinnema commented on requirements.txt
> -django==1.11.23
eagle eye :-) 
I've pushed the pygeppetto-django PR https://github.com/MetaCell/pygeppetto-django/pull/19 
pygeppetto-django branch geppetto-scidash is rebased on development

fixed this requirements.txt
should be fine now (also when we compile requirements.in again)

2020-01-15 19:36 UTC, zsinnema commented on requirements.txt
> -django==1.11.23
see https://github.com/MetaCell/scidash/blob/80febd741d10780df81db5f8b2796eeff1422c9c/requirements.txt#L31

2020-01-16 09:49 UTC, ddelpiano approved these changes

2020-01-16 09:49 UTC, merged