Feature/418
MetaCell/scidash pull request #152
Opened 2020-01-19 22:04 UTC by jrmartin

Adds ID to password-reset button. Adds jquery to base-template.html, since other templates using the base-template.html require jquery, gets rid of console errors while user login and sign up. Re-arranges import of base-template in other templates to be the first thing that's loaded, since subsequent imports need jquery loaded first.

2020-02-03 16:40 UTC, ddelpiano requested changes
@jrmartin this is good for me, I just need a clean-up of the branches you hardcoded (I guess to build your local env). Thx!

2020-02-03 16:40 UTC, ddelpiano commented on service/docker/Dockerfile-scidash
> +ARG targetBranch=feature/418
@jrmartin could you revert these changes? these should not be committed I think.

2020-02-03 16:40 UTC, ddelpiano commented on service/scripts/install-frontend.sh
> +geppetto_branch="scidash-jest-changes"
@jrmartin same here

2020-02-04 04:17 UTC, jrmartin commented
@ddelpiano Hard coded paths removed

2020-02-04 17:18 UTC, ddelpiano approved these changes

2020-02-04 17:18 UTC, merged